services:
  rails:
    image: ghcr.io/juliandrp/chatwoodopv:main
    depends_on:
      redis:
        condition: service_started
    environment:
      - SERVICE_FQDN_RAILS_3000=conversa.oportunidaddevida.com
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - FRONTEND_URL=https://conversa.oportunidaddevida.com
      - FORCE_SSL=true
      - ENABLE_ACCOUNT_SIGNUP=false
      - REDIS_URL=redis://default:${REDIS_PASSWORD}@redis:6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - POSTGRES_DATABASE=${POSTGRES_DB:-chatwoot}
      - POSTGRES_HOST=${POSTGRES_HOST:-pgc4ck4ck8s48w84s40koc48}
      - POSTGRES_USERNAME=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - RAILS_MAX_THREADS=5
      - ACTIVE_STORAGE_SERVICE=local
      - GOOGLE_GEMINI_API_KEY=${GOOGLE_GEMINI_API_KEY}
      - MAILER_SENDER_EMAIL=${MAILER_SENDER_EMAIL:-Conversa <noreply@oportunidaddevida.com>}
      - SMTP_ADDRESS=${SMTP_ADDRESS}
      - SMTP_PORT=${SMTP_PORT:-587}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_ENABLE_STARTTLS_AUTO=true
      - RAILS_LOG_TO_STDOUT=enabled
    entrypoint: docker/entrypoints/rails.sh
    command: sh -c "bundle exec rails db:chatwoot_prepare && bundle exec rails s -p 3000 -b 0.0.0.0"
    volumes:
      - storage_data:/app/storage
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://127.0.0.1:3000"]
      interval: 10s
      timeout: 10s
      retries: 15
      start_period: 180s
    networks:
      default:
      coolify:
        aliases:
          - rails-conversa
    restart: always

  sidekiq:
    image: ghcr.io/juliandrp/chatwoodopv:main
    depends_on:
      redis:
        condition: service_started
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - FRONTEND_URL=https://conversa.oportunidaddevida.com
      - FORCE_SSL=true
      - REDIS_URL=redis://default:${REDIS_PASSWORD}@redis:6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - POSTGRES_DATABASE=${POSTGRES_DB:-chatwoot}
      - POSTGRES_HOST=${POSTGRES_HOST:-pgc4ck4ck8s48w84s40koc48}
      - POSTGRES_USERNAME=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - ACTIVE_STORAGE_SERVICE=local
      - GOOGLE_GEMINI_API_KEY=${GOOGLE_GEMINI_API_KEY}
      - RAILS_LOG_TO_STDOUT=enabled
    command: ["bundle", "exec", "sidekiq", "-C", "config/sidekiq.yml"]
    volumes:
      - storage_data:/app/storage
    restart: always

  redis:
    image: redis:alpine
    restart: always
    command: ["sh", "-c", "redis-server --requirepass \"$REDIS_PASSWORD\""]
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - redis_data:/data

volumes:
  storage_data:
  redis_data:

networks:
  default:
  coolify:
    external: true
    name: coolify
